name: Build for Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Env
      env:
        VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}

    - name: Build & copy to gh-pages branch
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'vpodolyan'
        reponame: 'currency-viewer-vue'
        useyarn: true
        token: ${{ secrets.GITHUB_TOKEN }}
